// ─── Mock Data ────────────────────────────────────────────────────────────────
// In a real app this would come from your backend. Kept here so api.js can
// simulate network calls without touching component code.

export const MEETINGS = [
  { id: 1, title: "Q3 Product Roadmap Review", date: "2025-06-18", duration: "52 min", status: "Completed", attendees: ["Alice", "Bob", "Carol"], summary: "Discussed feature prioritization for Q3, agreed on mobile-first approach, and reviewed competitor analysis. Key focus areas: search performance, AI integration, and user onboarding improvements.", transcript: "Alice: Let's start with the Q3 priorities. We need to finalize which features make the cut. Bob: I think mobile-first is non-negotiable at this point. Our mobile traffic is 68% of total. Carol: Agreed. Search performance is also critical — we're seeing drop-off on slow searches...", action_items: [{ task: "Finalize mobile redesign specs", owner: "Bob", deadline: "2025-06-25", priority: "High", status: "In Progress" }, { task: "Run search performance audit", owner: "Carol", deadline: "2025-06-22", priority: "High", status: "Completed" }, { task: "Prepare competitor analysis deck", owner: "Alice", deadline: "2025-06-30", priority: "Medium", status: "Pending" }], key_decisions: "1. Mobile-first approach adopted for Q3 redesign.\n2. Search performance improvement prioritized over new features.\n3. AI integration scoped for Q4 only.", open_questions: "• What is the budget allocation for mobile redesign?\n• Will the AI integration require a new vendor partnership?" },
  { id: 2, title: "Engineering Sprint Planning", date: "2025-06-17", duration: "38 min", status: "Completed", attendees: ["Dave", "Eve", "Frank"], summary: "Sprint 24 planning session. Agreed on 42 story points, assigned tickets, and flagged three blockers related to API rate limits.", transcript: "Dave: We have 42 story points to allocate this sprint. Let's start with the critical path items. Eve: The auth refactor needs to land this sprint — it's blocking three other tickets. Frank: API rate limit issue is a concern. We might need to talk to the vendor...", action_items: [{ task: "Auth system refactor", owner: "Eve", deadline: "2025-06-24", priority: "Critical", status: "In Progress" }, { task: "Contact API vendor re: rate limits", owner: "Frank", deadline: "2025-06-20", priority: "High", status: "Completed" }, { task: "Update sprint board", owner: "Dave", deadline: "2025-06-18", priority: "Low", status: "Completed" }], key_decisions: "1. Sprint 24 capped at 42 story points.\n2. Auth refactor is top priority.\n3. API rate limit escalated to vendor.", open_questions: "• Will vendor respond before sprint ends?\n• Is Eve available for the full sprint?" },
  { id: 3, title: "Client Onboarding — Acme Corp", date: "2025-06-15", duration: "61 min", status: "Completed", attendees: ["Grace", "Henry", "Isla"], summary: "Initial onboarding for Acme Corp. Walked through platform features, set up their workspace, and identified custom integration requirements.", transcript: "Grace: Welcome to the platform! Let me walk you through the key features. Henry: We'll need SSO integration — that's a requirement from our IT team. Isla: We also have a Salesforce dependency for the CRM data sync...", action_items: [{ task: "Set up SSO integration", owner: "Grace", deadline: "2025-06-28", priority: "High", status: "Pending" }, { task: "Salesforce connector documentation", owner: "Isla", deadline: "2025-07-01", priority: "Medium", status: "Pending" }], key_decisions: "1. SSO is required before go-live.\n2. Salesforce connector to be custom-built.\n3. Go-live target: July 15.", open_questions: "• Which SSO provider does Acme use?\n• Is there a Salesforce API key available?" },
  { id: 4, title: "AI Features Brainstorm", date: "2025-06-12", duration: "45 min", status: "Completed", attendees: ["Jack", "Karen", "Leo"], summary: "Brainstormed 12 AI feature ideas. Top three selected for prototyping: smart task assignment, meeting sentiment analysis, and deadline prediction.", transcript: "Jack: Let's go broad first. What AI features would make the product genuinely magical? Karen: Auto-assigning tasks based on meeting content would save so much manual work. Leo: Sentiment analysis across meetings could be a great executive dashboard feature...", action_items: [{ task: "Prototype smart task assignment", owner: "Jack", deadline: "2025-06-30", priority: "High", status: "In Progress" }, { task: "Research sentiment APIs", owner: "Karen", deadline: "2025-06-25", priority: "Medium", status: "In Progress" }, { task: "Create deadline prediction model spec", owner: "Leo", deadline: "2025-07-05", priority: "Medium", status: "Pending" }], key_decisions: "1. Three AI features selected for prototyping.\n2. Timeline: 4-week prototype sprint.\n3. Karen leads sentiment analysis research.", open_questions: "• Which ML framework to use?\n• Do we need external AI vendor or build in-house?" },
  { id: 5, title: "Weekly Standup — Design Team", date: "2025-06-10", duration: "18 min", status: "Completed", attendees: ["Mia", "Noah", "Olivia"], summary: "Quick sync on design deliverables. Two designs approved, one pending revision. Figma handoff scheduled for Friday.", transcript: "Mia: Dashboard redesign is approved and ready for dev handoff. Noah: The onboarding flow needs one more revision — feedback from user testing came in late. Olivia: I'll have the mobile nav finalized by Thursday...", action_items: [{ task: "Revise onboarding flow", owner: "Noah", deadline: "2025-06-13", priority: "Medium", status: "Completed" }, { task: "Finalize mobile nav", owner: "Olivia", deadline: "2025-06-12", priority: "High", status: "Completed" }], key_decisions: "1. Dashboard redesign approved.\n2. Onboarding flow revision due Thursday.\n3. Figma handoff Friday noon.", open_questions: "• Will dev team be available for handoff on Friday?" },
  { id: 6, title: "Budget Review — H2 Planning", date: "2025-06-08", duration: "72 min", status: "Completed", attendees: ["Paul", "Quinn", "Rachel"], summary: "H2 budget review. Engineering allocation increased by 15%, marketing reduced by 8%. New AI tooling budget approved at $45K.", transcript: "Paul: Let's review the H2 budget proposals. Engineering is requesting a 15% increase due to the AI initiative. Quinn: Marketing can absorb an 8% reduction — we're shifting to organic growth strategies. Rachel: The $45K AI tooling budget is approved pending CFO sign-off...", action_items: [{ task: "Get CFO sign-off on AI budget", owner: "Rachel", deadline: "2025-06-15", priority: "Critical", status: "Completed" }, { task: "Update H2 budget spreadsheet", owner: "Paul", deadline: "2025-06-10", priority: "Medium", status: "Completed" }], key_decisions: "1. Engineering budget +15%.\n2. Marketing budget -8%.\n3. AI tooling: $45K approved.", open_questions: "• When will the AI vendor contracts be signed?" },
];

export const ALL_TASKS = MEETINGS.flatMap(m => m.action_items.map(t => ({ ...t, meeting: m.title })));

export const ANALYTICS_DATA = {
  taskStatus: [
    { name: "Completed", value: 8, color: "#1D9E75" },
    { name: "In Progress", value: 5, color: "#3266ad" },
    { name: "Pending", value: 4, color: "#D85A30" },
  ],
  meetingsPerMonth: [
    { month: "Jan", meetings: 12 }, { month: "Feb", meetings: 18 }, { month: "Mar", meetings: 15 },
    { month: "Apr", meetings: 22 }, { month: "May", meetings: 19 }, { month: "Jun", meetings: 24 },
  ],
  productivity: [
    { name: "Alice", score: 92 }, { name: "Bob", score: 87 }, { name: "Carol", score: 95 },
    { name: "Dave", score: 78 }, { name: "Eve", score: 88 }, { name: "Frank", score: 82 },
  ],
  deadlineCompliance: [
    { week: "Wk 1", onTime: 8, late: 2 }, { week: "Wk 2", onTime: 6, late: 4 },
    { week: "Wk 3", onTime: 9, late: 1 }, { week: "Wk 4", onTime: 7, late: 3 },
  ],
};
